---
title: Diegetic Games - Randy Lubin's Game Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: page
email: randy@diegeticgames.com
description: Diegetic Games is Randy Lubin's game studio, full of RPGs, larps, and
  other storytelling games. There are free print and play games, including drafts
  of upcoming releases.
sass:
  sass_dir: css
url: http://diegeticgames.com
twitter_username: diegeticgames
github_username: randylubin
markdown: kramdown
