# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diegetic Games, RPGs, Story Games, Storytelling
email: randy@diegeticgames.com
description: Diegetic Games is Randy Lubin's game studio, full of RPGs and other story games. There are free print and play games, including drafts of upcoming releases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diegeticgames.com" # the base hostname & protocol for your site
twitter_username: diegeticgames
github_username:  randylubin

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
