---
title: Diegetic Games, RPGs, Story Games, Storytelling
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: randy@diegeticgames.com
description: Diegetic Games is Randy Lubin's game studio, full of RPGs and other story
  games. There are free print and play games, including drafts of upcoming releases.
baseurl: ''
url: http://diegeticgames.com
twitter_username: diegeticgames
github_username: randylubin
markdown: kramdown
gems:
- jekyll-sitemap
